- name: Install tuned (the same tuning engine in OKD)
  ansible.builtin.apt:
      name: tuned
      state: present

- name: Create the custom performance profile
  ansible.builtin.file:
      path: /etc/tuned/srsran-performance
      state: directory
      owner: root
      group: root
      mode: "0755"

- name: Build the tuning configuration
  ansible.builtin.copy:
      dest: /etc/tuned/srsran-performance/tuned.conf
      owner: root
      group: root
      mode: "0644"
      content: |
          [main]
          summary=SRS tuned profile for RKE2
          include=network-latency

          [cpu]
          force_latency=1
          governor=performance
          energy_perf_bias=performance
          min_perf_pct=100

          [vm]
          # If a workload mostly uses anonymous memory and it hits this limit,
          # the entire working set is buffered for I/O, and any more write buffering
          # would require swapping, so it's time to throttle writes
          # until I/O can catch up.  Workloads that mostly use file mappings
          # may be able to use even higher values.
          #
          # The generator of dirty data starts writeback at this percentage
          # (system default is 20%)
          dirty_ratio=10
          # Start background writeback (via writeback threads) at this percentage
          # (system default is 10%)
          dirty_background_ratio=3
          # The swappiness parameter controls the tendency of the kernel to move
          # processes out of physical memory and onto the swap disk.
          # 0 tells the kernel to avoid swapping processes out of physical memory
          # for as long as possible
          # 100 tells the kernel to aggressively swap processes out of physical memory
          # and move them to swap cache
          swappiness=10
          transparent_hugepages=never

          [sysctl]
          kernel.sched_rt_runtime_us=980000
          # Busy polling helps reduce latency in the network receive path
          # by allowing socket layer code to poll the receive queue of a
          # network device, and disabling network interrupts.
          # busy_read value greater than 0 enables busy polling. Recommended
          # net.core.busy_read value is 50.
          # busy_poll value greater than 0 enables polling globally.
          # Recommended net.core.busy_poll value is 50
          net.core.busy_poll=50
          net.core.busy_read=50
          # TCP fast open reduces network latency by enabling data exchange
          # during the sender's initial TCP SYN. The value 3 enables fast open
          # on client and server connections.
          net.ipv4.tcp_fastopen=3
          # Upper limit on the number of independent inotify monitoring istances
          # for a single user
          fs.inotify.max_user_instances=256
          # Software ingress queues and synchronous polling
          net.core.rmem_default=134217728
          net.core.rmem_max=134217728
          net.core.wmem_default=134217728
          net.core.wmem_max=134217728

          [net]
          devices=enp65s0f0np0,enp65s0f1np1
          ring_rx=4096
          ring_tx=4096

- name: Check currently actived tuning profiles
  ansible.builtin.command: tuned-adm active
  register: tuned_current
  # Only reading, no change is performed
  changed_when: false
  failed_when: false

- name: Activate the tuning profile
  ansible.builtin.command: tuned-adm profile srsran-performance
  # Execute only if currently not activated
  when: "'srsran-performance' not in tuned_current.stdout"

- name: Update kernel parameters in GRUB
  vars:
      grub_params:
          - "skew_tick=1"
          - "nosoftlockup"
          - "nmi_watchdog=0"
          - "crashkernel=auto"
          - "softlockup_panic=0"
          - "audit=0"
          - "mce=off"
          - "mitigations=off" # Pay attention to the security matter
          - "tsc=nowatchdog"
          - "tsc=reliable"
          - "intel_iommu=on"
          - "iommu=pt"
          # CPU isolation
          - "isolcpus=3-11,14-23"
          - "nohz_full=3-11,14-23"
          - "rcu_nocbs=3-11,14-23"
          - "kthread_cpus=0-1,12-13"
          - "irqaffinity=0-1,12-13"
          - "rcu_nocb_poll"
          # Hugepages (1G x 16 = 16GB RAM are reserved)
          - "default_hugepagesz=1G"
          - "hugepagesz=1G"
          - "hugepages=16"
  ansible.builtin.copy:
      dest: /etc/default/grub.d/99-srsran.cfg
      content: |
          GRUB_CMDLINE_LINUX_DEFAULT="{{ grub_params | join(' ') }}"
      owner: root
      group: root
      mode: "0644"
  notify: Update-GRUB

# Update kernel configuration for N3xx USRPs (see OpenAirInterface docs)
- name: Configure sysctl net.core.wmem_max
  ansible.posix.sysctl:
      name: net.core.wmem_max
      value: "25000000"
      state: present
      reload: true
