dbURI: "mongodb://{{ .Release.Name }}-mongodb/open5gs"

populate:
    enabled: true
    image:
        registry: docker.io
        repository: gradiant/open5gs-dbctl
        tag: 0.10.3
        pullPolicy: IfNotPresent
    initCommands:
        - open5gs-dbctl add_ue_with_apn 999910000000001 3114A38F43110BFD775B8D97F8493CAB 7E9CF00650C37664C73FC7391B9BB4DB tenant1
        - open5gs-dbctl add_ue_with_apn 999910000000002 01ABB814C204DC9354E9C206E00F0979 8010EE2A3BF23B140FC6FEF9F1CEA2CE tenant1
        - open5gs-dbctl add_ue_with_apn 999910000000003 CE9B68E29520804CCFF3C87013AAEBC8 3A06FAD835D91C12160F298458820600 tenant1
        - open5gs-dbctl add_ue_with_apn 999920000000001 DA40AA0E1663C9B6E8E0B7DD1775A5D4 53407D8972223590280DF61CA9A9FBCD tenant2
        - open5gs-dbctl add_ue_with_apn 999920000000002 EFFA30163D68A796D7BDFA0F5589113D B135331676A01E4BBD17EC3B894A9C79 tenant2
        - open5gs-dbctl add_ue_with_apn 999920000000003 94991524E412EF299B7C0F65162215FC 6B21C567C16BD71041FD31A08CCA770E tenant2
        #- open5gs-dbctl add_ue_with_apn 999940000000001 fec86ba6eb707ed08905757b1bb44b8f C42449363BBAD02B66D16BC975D77CC1 tenant4
        #- open5gs-dbctl add_ue_with_apn 999950000000001 DA40AA0E1663C9B6E8E0B7DD1775A5D4 53407D8972223590280DF61CA9A9FBCD tenant5
        #- open5gs-dbctl add_ue_with_apn 999950000000002 EFFA30163D68A796D7BDFA0F5589113D B135331676A01E4BBD17EC3B894A9C79 tenant5

# Common
mongodb:
    enabled: true
    persistence:
        enabled: false
    auth:
        enabled: false
smf:
    enabled: true
    config:
        logLevel: info
        scp:
            enabled: true
        pcrf:
            enabled: false
        frdi:
            hostname: "" # if empty default is autogenerated open5gs svc fullname
            port: 3868
        dnsList:
            - 8.8.8.8
            - 8.8.4.4
            - 2001:4860:4860::8888
            - 2001:4860:4860::8844
        subnetList:
            - subnet: 10.45.0.0/24
              gateway: 10.45.0.1
              dnn: oai
            - subnet: 10.45.1.0/24
              gateway: 10.45.1.1
              dnn: tenant1
            - subnet: 10.45.2.0/24
              gateway: 10.45.2.1
              dnn: tenant2
            - subnet: 10.45.3.0/24
              gateway: 10.45.3.1
              dnn: tenant3
            - subnet: 10.45.4.0/24
              gateway: 10.45.4.1
              dnn: tenant4
            - subnet: 10.45.5.0/24
              gateway: 10.45.5.1
              dnn: tenant5
            - subnet: 10.45.6.0/24
              gateway: 10.45.6.1
              dnn: tenant6
        mtu: 1400
        info: # <--- ADD THIS BLOCK
            - s_nssai: # Info block for Slice 1 / DNNs
                  - sst: 1
                    dnn: [tenant1, tenant2, tenant3, tenant4, tenant5, tenant6] # List DNNs supported by this SMF for this slice
upf: # <-- Top-level key for the UPF sub-chart
    enabled: true
    config: # <-- .Values.config
        logLevel: info # <-- .Values.config.logLevel (Needed by template)
        upf: # <-- .Values.config.upf (Needed for gtpu path)
            gtpu: # <-- .Values.config.upf.gtpu
                dev: "" # <-- .Values.config.upf.gtpu.dev (Matches template)
                advertise: ""
        # Note: subnetList is NOT under config.upf anymore
        subnetList: # <-- Move subnetList directly under config: .Values.config.subnetList (Matches template)
            - subnet: 10.45.0.0/24
              gateway: 10.45.0.1
              dnn: oai
              dev: ogstun
              mask: 24
              createDev: true
              enableNAT: true
            - subnet: 10.45.1.0/24
              gateway: 10.45.1.1
              dnn: tenant1
              dev: ogstun
              mask: 24
              createDev: false
              enableNAT: true
            - subnet: 10.45.2.0/24
              gateway: 10.45.2.1
              dnn: tenant2
              dev: ogstun
              mask: 24
              createDev: false
              enableNAT: true
            - subnet: 10.45.3.0/24
              gateway: 10.45.3.1
              dnn: tenant3
              dev: ogstun
              mask: 24
              createDev: false
              enableNAT: true
            - subnet: 10.45.4.0/24
              gateway: 10.45.4.1
              dnn: tenant4
              dev: ogstun
              mask: 24
              createDev: false
              enableNAT: true
            - subnet: 10.45.5.0/24
              gateway: 10.45.5.1
              dnn: tenant5
              dev: ogstun
              mask: 24
              createDev: false
              enableNAT: true
            - subnet: 10.45.6.0/24
              gateway: 10.45.6.1
              dnn: tenant6
              dev: ogstun
              mask: 24
              createDev: false
              enableNAT: true
webui:
    ingress:
        hostname: open5gs.caravano.duckdns.org
    enabled: true

# 4G
hss:
    enabled: false
    mongodb:
        enabled: false
mme:
    enabled: false
pcrf:
    enabled: false
sgwc:
    enabled: false
sgwu:
    enabled: false

# 5G
amf:
    services:
        sbi:
            clusterIP: None
    enabled: true
    config:
        guamiList:
            - plmn_id:
                  mcc: "999"
                  mnc: "91"
              amf_id:
                  region: 2
                  set: 1
            - plmn_id:
                  mcc: "999"
                  mnc: "92"
              amf_id:
                  region: 2
                  set: 1
            - plmn_id:
                  mcc: "999"
                  mnc: "93"
              amf_id:
                  region: 2
                  set: 1
            - plmn_id:
                  mcc: "999"
                  mnc: "94"
              amf_id:
                  region: 2
                  set: 1
            - plmn_id:
                  mcc: "999"
                  mnc: "95"
              amf_id:
                  region: 2
                  set: 1
            - plmn_id:
                  mcc: "999"
                  mnc: "96"
              amf_id:
                  region: 2
                  set: 1
        taiList:
            - plmn_id:
                  mcc: "999"
                  mnc: "91"
              tac: [1]
            - plmn_id:
                  mcc: "999"
                  mnc: "92"
              tac: [1]
            - plmn_id:
                  mcc: "999"
                  mnc: "93"
              tac: [1]
            - plmn_id:
                  mcc: "999"
                  mnc: "94"
              tac: [1]
            - plmn_id:
                  mcc: "999"
                  mnc: "95"
              tac: [1]
            - plmn_id:
                  mcc: "999"
                  mnc: "96"
              tac: [1]
        plmnList:
            - plmn_id:
                  mcc: "999"
                  mnc: "91"
              s_nssai:
                  - sst: 1
            - plmn_id:
                  mcc: "999"
                  mnc: "92"
              s_nssai:
                  - sst: 1
            - plmn_id:
                  mcc: "999"
                  mnc: "93"
              s_nssai:
                  - sst: 1
            - plmn_id:
                  mcc: "999"
                  mnc: "94"
              s_nssai:
                  - sst: 1
            - plmn_id:
                  mcc: "999"
                  mnc: "95"
              s_nssai:
                  - sst: 1
            - plmn_id:
                  mcc: "999"
                  mnc: "96"
              s_nssai:
                  - sst: 1
    networkName: Gradiant

ausf:
    enabled: true
bsf:
    enabled: true
nrf:
    enabled: true
    config:
        servingList:
            - plmn_id:
                  mcc: 999
                  mnc: 91
            - plmn_id:
                  mcc: 999
                  mnc: 92
            - plmn_id:
                  mcc: 999
                  mnc: 93
            - plmn_id:
                  mcc: 999
                  mnc: 94
            - plmn_id:
                  mcc: 999
                  mnc: 95
            - plmn_id:
                  mcc: 999
                  mnc: 96
nssf:
    enabled: true
    config:
        nsiList:
            - nrf:
                  hostname: "open5gs-nrf-sbi" # Default if empty
                  port: 7777
              sst: 1

pcf:
    enabled: true
    mongodb:
        enabled: false
scp:
    enabled: true
    mongodb:
        enabled: false
udm:
    enabled: true
udr:
    enabled: true
    mongodb:
        enabled: false
