# Make sure Ansible host has access to these devices

[servers]
server1 ansible_host=192.168.1.101
# Our use-case requires only a single node deployment, but, as typically observed in Kubernetes clusters, it can be expanded to more servers (control planes) and agents (workers)
# acting on the following variables and recovering the original add-agent roles and variables (see commit history)
# server2 ansible_host=192.168.2.102
# server3 ansible_host=192.168.3.103

[agents]
# Our use-case requires only a single node deployment, but, as typically observed in Kubernetes clusters, it can be expanded to more servers (control planes) and agents (workers)
# acting on the following variables and recovering the original add-agent roles and variables (see commit history)
# agent1 ansible_host=192.168.1.150
# agent2 ansible_host=192.168.2.150

[rke2]

[rke2:children]
servers
# agents

[rke2:vars]
ansible_user=polimi
