#
#                  Politecnico di Milano
#
#         Student: Caravano Andrea
#            A.Y.: 2025/2026
#
#   Last modified: 11/05/2026
#
#     Description: Redis PersistentVolumeClaim declaration sketch
#                  This configuration is suited only for single or fixed node clusters, since it exploits local storage
#                  In case of a real distributed configuration, consider deploying distributed storage solutions (e.g. Longhorn)
#

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: redis-data-redis-master-0
    namespace: redis
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 8Gi # This should be <= the size of the PV
    storageClassName: manual # This must match the PV's storageClassName
